name: Tests
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    strategy:
      matrix:
        python-version: [3.9, 3.11]
        runs-on: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3
    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: 📥 Install test dependencies
      run: |
        pip install poetry
        PYTHON=python${{ matrix.python-version }} make venv
    - name: 🪄 Lint
      run: |
        pip install poetry
        PYTHON=python${{ matrix.python-version }} make lint
    - name: 🧪 Tests
      run: |
        pip install poetry
        PYTHON=python${{ matrix.python-version }} make unit-tests
